theme: jekyll-theme-midnight
name: PyQtricksz
title: PyQtricks
markdown: kramdown
highlighter: rouge
dateFormat: "%Y-%m-%d"
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/:num/"
github:
    is_project_page: false
