theme: jekyll-theme-midnight
name: PyQtricks
title: PyQtricks
markdown: kramdown
highlighter: rouge

date_format: "%Y-%m-%d"
excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/:num/"

github:
    is_project_page: false
